# Generated by Django 4.1.3 on 2022-12-04 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profit_list',
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 4, 14, 33, 10, 21109, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
