# Generated by Django 4.1.4 on 2023-01-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0003_alter_profile_plan_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='phone_number',
            field=models.CharField(blank=True, default='000000000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='bitcoin_address',
            field=models.CharField(blank=True, default='wallet address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='etherum_address',
            field=models.CharField(blank=True, default='wallet address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='litecoin_address',
            field=models.CharField(blank=True, default='wallet address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='xrp_address',
            field=models.CharField(blank=True, default='wallet address', max_length=100, null=True),
        ),
    ]
