# Generated by Django 4.1.4 on 2023-01-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_core", "0004_alter_site_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="face_reg_image",
            field=models.ImageField(
                blank=True, default="nil.jpg", null=True, upload_to="face_reg_images"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="r.jpg", null=True, upload_to="profile_images"
            ),
        ),
    ]
