# Generated by Django 4.1.4 on 2023-01-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_core", "0005_profile_face_reg_image_alter_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="face_reg_image",
            new_name="face_image",
        ),
    ]
